// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  //컴퓨터공학
  dataBaseSidebar: [{type: 'autogenerated', dirName: 'computer-since/0_data-base'}],
  softwareEngineeringSidebar:[{type: 'autogenerated', dirName: 'computer-since/1_software-engineering'}],
  dataStructureSidebar:[{type: 'autogenerated', dirName: 'computer-since/2_data-structure'}],
  comStructureSidebar:[{type: 'autogenerated', dirName: 'computer-since/3_computer-structure'}],
  cLanguageSidebar:[{type: 'autogenerated', dirName: 'computer-since/4_c-language'}],

  //웹프론트
  reactSidebar:[{type: 'autogenerated', dirName: 'web-front/0_react'}],
  nextJsSidebar:[{type: 'autogenerated', dirName: 'web-front/1_next-js'}],
  tailwindCssSidebar:[{type: 'autogenerated', dirName: 'web-front/2_tailwind-css'}],
  gsapSidebar:[{type: 'autogenerated', dirName: 'web-front/3_gsap'}],
  threeJsSidebar:[{type: 'autogenerated', dirName: 'web-front/4_three-js'}],
  typeScriptSidebar:[{type: 'autogenerated', dirName: 'web-front/5_type-script'}],
  charJsSidebar:[{type: 'autogenerated', dirName: 'web-front/6_chart-js'}],



  //웹백엔드
  laravelSidebar:[{type: 'autogenerated', dirName: 'web-back/0_laravel'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
