// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

// @ts-check

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 기본 사이드바
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 1. 컴퓨터공학 (폴더명: computer-since)
  dataBaseSidebar: [{type: 'autogenerated', dirName: 'computer-since/0_data-base'}],
  softwareEngineeringSidebar: [{type: 'autogenerated', dirName: 'computer-since/1_software-engineering'}],
  dataStructureSidebar: [{type: 'autogenerated', dirName: 'computer-since/2_data-structure'}],
  comStructureSidebar: [{type: 'autogenerated', dirName: 'computer-since/3_computer-structure'}],
  cLanguageSidebar: [{type: 'autogenerated', dirName: 'computer-since/4_c-language'}],
  informationProcessingSidebar: [{type: 'autogenerated', dirName: 'computer-since/5_information-cer'}], // cer 확인
  networkManagerSidebar: [{type: 'autogenerated', dirName: 'computer-since/6_network-cer'}], // cer 확인
  pcMaintenanceSidebar: [{type: 'autogenerated', dirName: 'computer-since/7_pc-mechanic-cer'}], // mechanic-cer 확인
  sqldSidebar: [{type: 'autogenerated', dirName: 'computer-since/8_sqld-cer'}], // sqld-cer 확인

  // 2. 웹프론트 (폴더명: web-front)
  reactSidebar: [{type: 'autogenerated', dirName: 'web-front/0_react'}],
  nextJsSidebar: [{type: 'autogenerated', dirName: 'web-front/1_next-js'}],
  tailwindCssSidebar: [{type: 'autogenerated', dirName: 'web-front/2_tailwind-css'}],
  gsapSidebar: [{type: 'autogenerated', dirName: 'web-front/3_gsap'}],
  threeJsSidebar: [{type: 'autogenerated', dirName: 'web-front/4_three-js'}],
  typeScriptSidebar: [{type: 'autogenerated', dirName: 'web-front/5_type-script'}],
  charJsSidebar: [{type: 'autogenerated', dirName: 'web-front/6_char-js'}], // 폴더명 char-js 유지
  javascriptSidebar: [{type: 'autogenerated', dirName: 'web-front/7_javascript'}],
  reactNativeSidebar: [{type: 'autogenerated', dirName: 'web-front/8_react-native'}],


  // 3. 웹백엔드 (폴더명: web-back)
  laravelSidebar: [{type: 'autogenerated', dirName: 'web-back/0_laravel'}],
  codeIgniterSidebar: [{type: 'autogenerated', dirName: 'web-back/1_code-igniter'}],

  // 4. 독학사 (폴더명: self-taught)
  basicStatisticsSidebar: [{type: 'autogenerated', dirName: 'self-taught/0_basic-statistics'}],
  basicMathSidebar: [{type: 'autogenerated', dirName: 'self-taught/1_basic-math'}],
  basicEnglishSidebar: [{type: 'autogenerated', dirName: 'self-taught/2_basic-english'}],
  basicKoreanSidebar: [{type: 'autogenerated', dirName: 'self-taught/3_basic-korean'}],
  basicHistorySidebar: [{type: 'autogenerated', dirName: 'self-taught/4_basic-korean-history'}], // korean-history 확인
  basicLawSidebar: [{type: 'autogenerated', dirName: 'self-taught/5_basic-introduction-raw'}], // introduction-raw 확인

  // 5. 디자인 (폴더명: design)
  photoshopSidebar: [{type: 'autogenerated', dirName: 'design/0_photoshop'}],
  illustratorSidebar: [{type: 'autogenerated', dirName: 'design/1_illustrator'}],
  afterEffectsSidebar: [{type: 'autogenerated', dirName: 'design/2_after-effect'}], // effect (단수) 확인
  premiereproSidebar: [{type: 'autogenerated', dirName: 'design/3_premiere-pro'}],
  blenderSidebar: [{type: 'autogenerated', dirName: 'design/4_blender'}],
  riveSidebar: [{type: 'autogenerated', dirName: 'design/5_rive'}],
  figmaSidebar: [{type: 'autogenerated', dirName: 'design/6_figma'}],
  serviceExperienceDesignSidebar: [{type: 'autogenerated', dirName: 'design/7_service-design'}],
  visualDesignSidebar: [{type: 'autogenerated', dirName: 'design/8_visual-design'}],
  colorListsidebar: [{type: 'autogenerated', dirName: 'design/9_color-list'}], // color-list 확인
  computerGrSidebar: [{type: 'autogenerated', dirName: 'design/10_computer-graphic'}], // graphic (단수) 확인
  webDesignSidebar: [{type: 'autogenerated', dirName: 'design/11_web-develop-design'}], // develop-design 확인
  multimediaSidebar: [{type: 'autogenerated', dirName: 'design/12_multi-media-design'}], // multi-media 확인

  // 6. ETC (폴더명: etc)
  etcMathSidebar: [{type: 'autogenerated', dirName: 'etc/0_math-dictionary'}],
  etcScienceSidebar: [{type: 'autogenerated', dirName: 'etc/1_since-dictionary'}], // since 확인
  etcEnglishSidebar: [{type: 'autogenerated', dirName: 'etc/2_english-dictionary'}],
};

export default sidebars;